name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - ydata-profiling
  - pyarrow=2.0
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - pip=23.3.1
  - scikit-learn=1.3.2
  - seaborn
  - jupyterlab=4.1.3
  - pip:
      - wandb==0.16.0
      - mlflow==2.8.1